export { default as Button } from "./Button"
export { default as Console } from "./Console"
export { default as Feature } from "./Feature"
export { default as GetStarted } from "./GetStarted"
export { default as Jumbotron } from "./Jumbotron"
export { default as Whatis } from "./Whatis"
